import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { MARKETS, getRandomTradingDate, generateHeadlines } from '../utils/mockData';
import './MarketSelectPage.css';

export default function MarketSelectPage() {
  const navigate = useNavigate();
  const [tradingDate, setTradingDate] = useState(null);
  const [showNews, setShowNews] = useState(false);
  const [newsSearch, setNewsSearch] = useState('');
  const [headlines, setHeadlines] = useState(null);
  const displayName = localStorage.getItem('tt_displayName') || 'Trader';
  const balance = parseInt(localStorage.getItem('tt_balance') || '1000');

  useEffect(() => {
    const date = getRandomTradingDate();
    setTradingDate(date);
    setHeadlines(generateHeadlines(date));
    localStorage.setItem('tt_tradingDate', date.toISOString());
  }, []);

  const handleSelectMarket = (marketId) => {
    navigate(`/trade/${marketId}`);
  };

  const categories = [...new Set(MARKETS.map(m => m.category))];

  if (!tradingDate) return null;

  const dateDisplay = tradingDate.toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const timeDisplay = tradingDate.toLocaleTimeString('en-US', {
    hour: '2-digit',
    minute: '2-digit',
    timeZoneName: 'short',
  });

  return (
    <div className="market-page">
      <header className="market-header">
        <div className="header-left">
          <div className="time-badge">
            <svg width="18" height="18" viewBox="0 0 18 18" fill="none">
              <circle cx="9" cy="9" r="8" stroke="#3b82f6" strokeWidth="1.5"/>
              <line x1="9" y1="4" x2="9" y2="9" stroke="#3b82f6" strokeWidth="1.5" strokeLinecap="round"/>
              <line x1="9" y1="9" x2="13" y2="11" stroke="#22c55e" strokeWidth="1.5" strokeLinecap="round"/>
            </svg>
            <span className="time-label">TIME TRADER</span>
          </div>
        </div>
        <div className="header-right">
          <div className="balance-badge">
            <span className="balance-icon">🪙</span>
            <span className="balance-amount">{balance.toLocaleString()}</span>
            <span className="balance-label">tokens</span>
          </div>
          <div className="user-badge">
            <span className="user-avatar">👤</span>
            <span>{displayName}</span>
          </div>
        </div>
      </header>

      <div className="date-banner">
        <div className="date-portal">
          <div className="portal-ring" />
          <div className="portal-ring ring-2" />
          <div className="portal-content">
            <span className="portal-label">YOU'VE TRAVELED TO</span>
            <h2 className="portal-date">{dateDisplay}</h2>
            <span className="portal-time">Market opens at {timeDisplay}</span>
          </div>
        </div>
        <div className="date-actions">
          <button className="news-btn" onClick={() => setShowNews(!showNews)}>
            📰 {showNews ? 'Hide' : 'View'} Daily Brief
          </button>
        </div>
      </div>

      {showNews && (
        <div className="news-overlay" onClick={() => setShowNews(false)}>
          <div className="news-panel" onClick={(e) => e.stopPropagation()}>
            <div className="news-header">
              <h3>📰 Daily Brief — {dateDisplay}</h3>
              <button className="news-close" onClick={() => setShowNews(false)}>✕</button>
            </div>
            <div className="news-search">
              <input
                type="text"
                placeholder="Search archived websites (Wayback Machine)..."
                value={newsSearch}
                onChange={(e) => setNewsSearch(e.target.value)}
              />
              <button className="search-go">🔍</button>
            </div>
            <div className="news-list">
              {headlines?.headlines.map((h, i) => (
                <div key={i} className="news-item">
                  <span className="news-category">{h.category}</span>
                  <div className="news-body">
                    <h4>{h.title}</h4>
                    <div className="news-meta">
                      <span>{h.source}</span>
                      <span>•</span>
                      <span>{h.time}</span>
                    </div>
                  </div>
                </div>
              ))}
            </div>
            <div className="news-footer">
              <p>Headlines generated by AI based on historical events</p>
            </div>
          </div>
        </div>
      )}

      <div className="market-grid-section">
        <h3 className="section-title">Select a Market to Trade</h3>
        <p className="section-sub">You have 24 hours from market open. Choose wisely.</p>

        {categories.map((cat) => (
          <div key={cat} className="market-category">
            <h4 className="cat-label">{cat}</h4>
            <div className="market-cards">
              {MARKETS.filter(m => m.category === cat).map((market) => (
                <button
                  key={market.id}
                  className="market-card"
                  onClick={() => handleSelectMarket(market.id)}
                >
                  <span className="market-icon">{market.icon}</span>
                  <div className="market-info">
                    <span className="market-name">{market.name}</span>
                    <span className="market-symbol">{market.symbol}</span>
                  </div>
                  <svg className="market-arrow" width="16" height="16" viewBox="0 0 16 16" fill="none">
                    <path d="M6 4l4 4-4 4" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                  </svg>
                </button>
              ))}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
